//! The Arden Code desktop app.

mod commands;
mod webview;
mod window;
mod window_state;

pub use window::startup_background;

use std::path::{Path, PathBuf};
use std::time::Duration;

use arden_core::paths::{AppPaths, DATA_DIR_VARIABLE};
use arden_diagnostics::redact::Redactor;
use arden_diagnostics::{crash, logging};
use arden_settings::service::SettingsService;
use arden_windows::preferences;
use specta_typescript::Typescript;
use tauri::Manager;
use tauri_specta::Event;
use tauri_specta::{Builder, ErrorHandlingMode, collect_commands, collect_events};

/// The typed contract between Rust and the UI.
fn specta_builder() -> Builder<tauri::Wry> {
    // A failed command makes the UI's promise reject with its `AppError`, instead of returning a
    // result object.
    let builder = Builder::<tauri::Wry>::new()
        .error_handling(ErrorHandlingMode::Throw)
        // One shape per type, the one Rust sends, instead of separate "serialize" and "deserialize"
        // versions for types whose fields have defaults.
        .disable_serde_phases();

    #[cfg(debug_assertions)]
    let commands = collect_commands![
        commands::app_info,
        commands::show_system_menu,
        commands::log_from_ui,
        commands::open_logs_folder,
        commands::redact_text,
        commands::get_settings,
        commands::change_setting,
        commands::reset_setting,
        commands::set_shortcuts,
        commands::reset_shortcuts,
        commands::take_settings_notice,
        commands::get_system_preferences,
        commands::debug_fail,
        commands::debug_panic,
    ];
    #[cfg(not(debug_assertions))]
    let commands = collect_commands![
        commands::app_info,
        commands::show_system_menu,
        commands::log_from_ui,
        commands::open_logs_folder,
        commands::redact_text,
        commands::get_settings,
        commands::change_setting,
        commands::reset_setting,
        commands::set_shortcuts,
        commands::reset_shortcuts,
        commands::take_settings_notice,
        commands::get_system_preferences,
    ];

    builder.commands(commands).events(collect_events![
        commands::SettingsChanged,
        commands::SystemPreferencesChanged
    ])
}

/// Writes the TypeScript bindings for every command to `path`.
///
/// # Errors
///
/// Returns an error when the bindings cannot be generated or written.
pub fn export_bindings(path: &Path) -> Result<(), specta_typescript::Error> {
    specta_builder().export(Typescript::default(), path)
}

/// The TypeScript module that holds the settings' defaults. Rust decides them; the UI shows these
/// only where there is no Rust to ask, such as a plain browser during development.
///
/// # Panics
///
/// Never in practice: the defaults are plain data that always serialize.
#[must_use]
pub fn defaults_module() -> String {
    let defaults = serde_json::to_string_pretty(&arden_settings::settings::Settings::default())
        .expect("the defaults are JSON");
    format!(
        "// Generated by `pnpm bindings` from the defaults in arden-settings. Do not edit.\nimport type {{ Settings }} from \"./bindings\";\n\nexport const defaultSettings: Settings = {defaults};\n"
    )
}

/// Writes [`defaults_module`] to `path`.
///
/// # Errors
///
/// Returns an error when the file cannot be written.
pub fn export_defaults(path: &Path) -> std::io::Result<()> {
    std::fs::write(path, defaults_module())
}

/// Where the app keeps its files: Windows' data folders, unless `ARDEN_CODE_DATA_DIR` points elsewhere.
fn resolve_paths(app: &tauri::App) -> tauri::Result<AppPaths> {
    let data_dir = std::env::var_os(DATA_DIR_VARIABLE).map(PathBuf::from);
    Ok(AppPaths::resolve(
        data_dir.as_deref(),
        &app.path().config_dir()?,
        &app.path().local_data_dir()?,
    ))
}

/// Starts logging and crash reporting, and returns the redactor that removes private details from
/// anything the user might share. Neither is worth stopping the app for if it fails.
fn start_diagnostics(app: &tauri::App, paths: &AppPaths) -> Redactor {
    let home = app.path().home_dir().ok();
    let user_folder = std::env::var("USERPROFILE").ok();
    let profile_folders: Vec<&str> = home
        .as_deref()
        .and_then(Path::to_str)
        .into_iter()
        .chain(user_folder.as_deref())
        .collect();

    let redactor = Redactor::new(&profile_folders);
    crash::install_panic_hook(
        &paths.crashes_dir(),
        env!("CARGO_PKG_VERSION"),
        redactor.clone(),
    );
    if let Err(error) = logging::init(&paths.logs_dir(), &profile_folders) {
        eprintln!("Arden Code could not start logging: {error}");
    } else {
        tracing::info!(version = env!("CARGO_PKG_VERSION"), "Arden Code started");
    }
    redactor
}

/// How often Windows' text size and regional format are looked at for a change.
const SYSTEM_PREFERENCES_INTERVAL: Duration = Duration::from_millis(1500);

/// Tells the UI when the person changes the text size or the regional format in Windows.
fn watch_system_preferences(handle: tauri::AppHandle) -> preferences::Watcher {
    preferences::Watcher::start(
        preferences::read(),
        SYSTEM_PREFERENCES_INTERVAL,
        preferences::read,
        move |now| {
            let _ = commands::SystemPreferencesChanged {
                preferences: now.clone().into(),
            }
            .emit(&handle);
        },
    )
}

/// Starts the app.
///
/// # Panics
///
/// Panics when the Tauri runtime fails to start.
pub fn run() {
    let builder = specta_builder();

    tauri::Builder::default()
        // This plugin must come first. A second launch ends here and brings the first window forward.
        .plugin(tauri_plugin_single_instance::init(
            |app, _arguments, _working_directory| {
                window::focus_main_window(app);
            },
        ))
        .plugin(tauri_plugin_clipboard_manager::init())
        .plugin(tauri_plugin_opener::init())
        .on_page_load(|_webview, payload| {
            tracing::info!(url = %payload.url(), event = ?payload.event(), "page load");
        })
        .invoke_handler(builder.invoke_handler())
        .setup(move |app| {
            builder.mount_events(app);
            let paths = resolve_paths(app)?;
            app.manage(start_diagnostics(app, &paths));
            let settings = SettingsService::start(&paths.config);
            let handle = app.handle().clone();
            settings.subscribe(move |settings, notice| {
                window::apply_native_theme(&handle, settings.appearance.theme);
                let _ = commands::SettingsChanged {
                    settings: settings.clone(),
                    notice: notice.cloned(),
                }
                .emit(&handle);
            });
            window::prepare_main_window(app, &paths, settings.get().appearance.theme)?;
            app.manage(settings);
            app.manage(paths);
            app.manage(watch_system_preferences(app.handle().clone()));
            Ok(())
        })
        .run(tauri::generate_context!())
        .expect("failed to run Arden Code");
}
