import { Script } from "node:vm";

import { affinityScript, brandLibrary, cubicSegments, readSvg } from "./affinity.ts";

describe("affinityScript", () => {
  const script = affinityScript();

  it("is JavaScript Affinity can run, and says it is made by the build", () => {
    expect(script.startsWith("// Generated by `pnpm brand:build`")).toBe(true);
    // Compiling it is the check: nothing runs.
    expect(() => new Script(script)).not.toThrow();
  });

  it("carries the whole library, so it needs no files next to it", () => {
    for (const board of brandLibrary().artboards) {
      expect(script).toContain(JSON.stringify(board.name));
    }
  });
});

describe("brandLibrary", () => {
  const library = brandLibrary();
  const artboard = (name: string) => library.artboards.find((board) => board.name === name);

  it("has an artboard for every logo file and every image made from the logo, then colors and type", () => {
    const logos = ["mark", "wordmark", "logo-horizontal", "logo-stacked"].flatMap((shape) =>
      ["color-on-light", "color-on-dark", "black", "white"].map((variant) => `${shape}-${variant}`),
    );
    expect(library.artboards.map((board) => board.name)).toEqual([
      ...logos,
      "app-icon-1024",
      "installer-header",
      "installer-sidebar",
      "readme-header-light",
      "readme-header-dark",
      "social-preview",
      "Colors",
      "Type",
    ]);
  });

  it("puts the logos made for dark backgrounds on the dark theme's background", () => {
    expect(artboard("mark-color-on-dark")?.backdrop).toBe("#0A0A0A");
    expect(artboard("logo-horizontal-white")?.backdrop).toBe("#0A0A0A");
    expect(artboard("readme-header-dark")?.backdrop).toBe("#0A0A0A");
    expect(artboard("mark-color-on-light")?.backdrop).toBeUndefined();
  });

  it("shows the light and dark colors of plan section 8.2 as swatches, with their values", () => {
    const colors = artboard("Colors");
    const fills = colors?.artwork.shapes.map((shape) => shape.fill);
    const labels = colors?.labels.map((label) => label.text).join(" ");

    for (const color of ["#EA9061", "#58382B", "#F2E8E1", "#FFFFFF", "#0A0A0A"]) {
      expect(fills).toContain(color);
      expect(labels).toContain(color);
    }
  });

  it("has a type sample in Lora, drawn as outlines so it needs no font installed", () => {
    const type = artboard("Type");

    expect(type?.artwork.shapes.length).toBeGreaterThan(3);
    expect(type?.labels.map((label) => label.text).join(" ")).toContain("Lora Regular");
  });
});

describe("readSvg", () => {
  it("reads a generated file: its size, its background and its shapes where they are placed", () => {
    const svg =
      '<svg xmlns="http://www.w3.org/2000/svg" width="100" height="50" viewBox="0 0 100 50">' +
      '<rect width="100" height="50" fill="#FFFFFF"/>' +
      '<g transform="translate(10 5) scale(0.5)"><path fill="#EA9061" d="M0 0L20 0L20 10Z"/></g>' +
      '<path fill="#58382B" d="M1 2L3 4"/></svg>';

    expect(readSvg(svg)).toEqual({
      width: 100,
      height: 50,
      background: "#FFFFFF",
      shapes: [
        { fill: "#EA9061", segments: [["M", 10, 5], ["L", 20, 5], ["L", 20, 10], ["Z"]] },
        {
          fill: "#58382B",
          segments: [
            ["M", 1, 2],
            ["L", 3, 4],
          ],
        },
      ],
    });
  });

  it("leaves out the background of a file that has none, as the logo files", () => {
    const svg =
      '<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 48.5 50" width="48.5" height="50">' +
      '<title>Arden Code</title><path fill="#EA9061" d="M0 0L1 1"/></svg>';

    expect(readSvg(svg)).toEqual({
      width: 48.5,
      height: 50,
      shapes: [
        {
          fill: "#EA9061",
          segments: [
            ["M", 0, 0],
            ["L", 1, 1],
          ],
        },
      ],
    });
  });
});

describe("cubicSegments", () => {
  it("keeps moves, lines and closes as they are", () => {
    expect(cubicSegments("M0 0L10 0L10 5Z")).toEqual([
      ["M", 0, 0],
      ["L", 10, 0],
      ["L", 10, 5],
      ["Z"],
    ]);
  });

  it("turns a quarter of a circle, as the mark's corners are, into one cubic curve", () => {
    // Radius 28 around (292, 72), from its right to its bottom: the handles are 28 × 0.5523 long.
    expect(cubicSegments("M320 72A28 28 0 0 1 292 100")).toEqual([
      ["M", 320, 72],
      ["C", 320, 87.464, 307.464, 100, 292, 100],
    ]);
  });

  it("turns a quadratic curve, as the letters are, into the same curve as a cubic one", () => {
    // The handles are two thirds of the way from each end to the quadratic's control point.
    expect(cubicSegments("M0 0Q30 60 60 0")).toEqual([
      ["M", 0, 0],
      ["C", 20, 40, 40, 40, 60, 0],
    ]);
  });

  it("refuses what the generator never writes, rather than drawing it wrong", () => {
    expect(() => cubicSegments("m0 0l10 0")).toThrow(/m/);
  });
});
