/** `pnpm brand:build`: writes every generated brand file. Output is deterministic. */

import { spawnSync } from "node:child_process";
import { mkdirSync, rmSync, writeFileSync } from "node:fs";
import { createRequire } from "node:module";
import path from "node:path";
import { fileURLToPath } from "node:url";

import { affinityScript } from "./affinity.ts";
import { buildRasterAssets } from "./assets.ts";
import { buildShapes } from "./lockups.ts";
import { buildLogoFiles } from "./logo-files.ts";

const repoRoot = fileURLToPath(new URL("../../", import.meta.url));
const write = (relativePath: string, contents: string | Uint8Array) => {
  const target = path.join(repoRoot, relativePath);
  mkdirSync(path.dirname(target), { recursive: true });
  writeFileSync(target, contents);
};

// SVG masters.
const svgFiles = buildLogoFiles();
for (const [name, svg] of Object.entries(svgFiles).toSorted(([a], [b]) => a.localeCompare(b))) {
  write(`brand/assets/svg/${name}`, svg);
}

// The Affinity script that draws the whole kit as a document (plan section 8.5).
write("brand/assets/affinity/build-brand-library.js", affinityScript());

// The app's <Logo />, <Mark /> and <Wordmark /> components draw these same outlines.
write(
  "apps/desktop/src/components/brand/logo-shapes.gen.ts",
  `// Generated by \`pnpm brand:build\`. Do not edit.\n\nexport const logoShapes = ${JSON.stringify(buildShapes(), null, 2)} as const;\n`,
);

// Icons, installer images, tray icons, favicon and GitHub images.
const assets = buildRasterAssets();
const master = "brand/assets/png/app-icon-1024.png";
write(master, assets[master] ?? new Uint8Array());

// Tauri's own generator makes its icon set from the 1024 px master...
const iconDirectory = "apps/desktop/src-tauri/icons";
const tauriCli = createRequire(path.join(repoRoot, "apps/desktop/package.json")).resolve(
  "@tauri-apps/cli/tauri.js",
);
const generated = spawnSync(
  process.execPath,
  [tauriCli, "icon", path.join(repoRoot, master), "-o", path.join(repoRoot, iconDirectory)],
  { cwd: repoRoot, stdio: "inherit" },
);
if (generated.status !== 0) {
  throw new Error("`tauri icon` failed");
}
// ...minus the platforms Arden Code does not ship on.
for (const unused of ["android", "ios", "icon.icns"]) {
  rmSync(path.join(repoRoot, iconDirectory, unused), { recursive: true, force: true });
}

// ...and then our hand-tuned icon.ico replaces the one Tauri made, with the rest of the assets.
for (const [relativePath, contents] of Object.entries(assets)) {
  write(relativePath, contents);
}

console.log(
  `wrote ${Object.keys(svgFiles).length} SVG files, the component outlines and ${Object.keys(assets).length} other assets`,
);
