/** `pnpm brand:build`: writes every generated brand file. Output is deterministic. */

import { mkdirSync, writeFileSync } from "node:fs";

import { buildLogoFiles } from "./logo-files.ts";
import { buildShapes } from "./lockups.ts";

const svgDirectory = new URL("../assets/svg/", import.meta.url);
mkdirSync(svgDirectory, { recursive: true });

const files = buildLogoFiles();
for (const [name, svg] of Object.entries(files).toSorted(([a], [b]) => a.localeCompare(b))) {
  writeFileSync(new URL(name, svgDirectory), svg);
}

// The app's <Logo />, <Mark /> and <Wordmark /> components draw these same outlines.
const componentsData = new URL(
  "../../apps/desktop/src/components/brand/logo-shapes.gen.ts",
  import.meta.url,
);
writeFileSync(
  componentsData,
  `// Generated by \`pnpm brand:build\`. Do not edit.\n\nexport const logoShapes = ${JSON.stringify(buildShapes(), null, 2)} as const;\n`,
);

console.log(`wrote ${Object.keys(files).length} SVG files and the component outlines`);
