// Generated by `pnpm bindings` from the defaults in arden-settings. Do not edit.
import type { Settings } from "./bindings";

export const defaultSettings: Settings = {
  "version": 1,
  "general": {
    "onStartup": "restore",
    "checkForUpdates": true,
    "regionalFormat": "windows"
  },
  "appearance": {
    "theme": "system",
    "zoom": 100,
    "followTextSize": true,
    "codeFontSize": 13,
    "codeLigatures": false,
    "reduceMotion": "system",
    "showStatusBar": true
  },
  "layout": {
    "sidebarWidth": 260,
    "inspectorWidth": 320
  },
  "keyboard": {
    "shortcuts": {}
  }
};
